-- Configurar contexto
USE DATABASE UCM;
USE SCHEMA SMART_DESK;

SELECT * FROM ACCOUNTS;
SELECT * FROM SALES;
SELECT * FROM FORECASTS;

-- CONSULTAS

-- 1. Análisis de Ventas y Beneficio por Categoría de Producto
SELECT
    CATEGORY AS CATEGORIA,
    SUM(MAINTENANCE) AS MANTENIMIENTO,
    SUM(PRODUCT) AS PRODUCTO,
    SUM(PARTS) AS PARTES,
    SUM(SUPPORT) AS SOPORTE,
    SUM(TOTAL) AS TOTAL_VENTAS,
    SUM(UNITS_SOLD) AS UNIDADES_VENDIDAS,
    SUM(PROFIT) AS BENEFICIO_TOTAL
FROM UCM.SMART_DESK.SALES
WHERE YEAR = 2020
  AND ACCOUNT = 'Adabs Entertainment'
GROUP BY CATEGORY
ORDER BY CATEGORY;



-- 2. Comparación de Rendimiento por País en Regiones APAC y EMEA

SELECT
    REGION,
    COUNTRY,
    AVG(TOTAL) AS INGRESO_PROMEDIO,
    AVG(UNITS_SOLD) AS UNIDADES_VENDIDAS_PROMEDIO,
    AVG(PROFIT) AS BENEFICIO_PROMEDIO
FROM UCM.SMART_DESK.ACCOUNTS ACCOUNTS JOIN UCM.SMART_DESK.SALES SALES 
ON ACCOUNTS.ACCOUNT=SALES.ACCOUNT

WHERE REGION IN ('APAC','EMEA')
GROUP BY REGION,COUNTRY
ORDER BY REGION, INGRESO_PROMEDIO DESC;



-- 3. Análisis del Beneficio Total por Industria: Estudio de Clientes en Etapa de Compromiso

SELECT 
    C.INDUSTRY AS INDUSTRIA,
    SUM(S.PROFIT) AS BENEFICIO_TOTAL,
    CASE 
        WHEN SUM(S.PROFIT) > 1000000 THEN 'ALTO'
        ELSE 'NORMAL'
    END AS CATEGORIA_SEGUN_BENEFICIO
FROM UCM.SMART_DESK.ACCOUNTS C
JOIN UCM.SMART_DESK.SALES S
    ON C.ACCOUNT = S.ACCOUNT
WHERE C.ACCOUNT IN (
        SELECT F.ACCOUNT
        FROM UCM.SMART_DESK.FORECASTS F
        WHERE F.FORECAST > 500000
          AND F.PREDICTION_CATEGORY = 'Commit'
)
GROUP BY C.INDUSTRY
ORDER BY BENEFICIO_TOTAL DESC;


-- 4. Evolución del Pronóstico y Beneficio Real: Análisis de la Trayectoria por Categoría.
SELECT
    COALESCE(s.CATEGORY, f.CATEGORY) AS CATEGORIA,
    SUM(s.PROFIT) AS SUMA_BENEFICIO_2021,
    SUM(f.FORECAST) AS PREVISION_BENEFICIO_2022,
    MIN(f.OPPORTUNITY_AGE) AS OPORTUNIDAD_MAS_RECIENTE,
    MAX(f.OPPORTUNITY_AGE) AS OPORTUNIDAD_MAS_ANTIGUA
FROM (
    SELECT *
    FROM UCM.SMART_DESK.SALES
    WHERE YEAR = 2021) s
    
FULL OUTER JOIN (
    SELECT *
    FROM UCM.SMART_DESK.FORECASTS
    WHERE YEAR = 2022) f
    
    ON s.CATEGORY = f.CATEGORY
GROUP BY COALESCE(s.CATEGORY, f.CATEGORY);




-- CASO PRACTICO

-- 1. Segmentación de Clientes

-- 2. Análisis Exploratorio

SELECT
    a.INDUSTRY,
    COUNT(DISTINCT a.ACCOUNT) AS NUM_CUENTAS,
    SUM(s.TOTAL) AS VENTAS_TOTALES,
    SUM(s.PROFIT) AS BENEFICIO_TOTAL
FROM UCM.SMART_DESK.ACCOUNTS a
JOIN UCM.SMART_DESK.SALES s
    ON a.ACCOUNT = s.ACCOUNT
GROUP BY a.INDUSTRY
ORDER BY VENTAS_TOTALES DESC;






-- 3. Respuesta a la Pregunta de Negocio (SQL)
// Margen de beneficio
SELECT
    a.INDUSTRY AS INDUSTRIA,
    SUM(s.TOTAL) AS VENTAS_TOTALES,
    SUM(s.UNITS_SOLD) AS UNIDADES_VENDIDAS,
    SUM(s.PROFIT) AS BENEFICIO_TOTAL,
    ROUND(SUM(s.PROFIT) / NULLIF(SUM(s.TOTAL), 0), 2) AS MARGEN
FROM UCM.SMART_DESK.ACCOUNTS a
JOIN UCM.SMART_DESK.SALES s
    ON a.ACCOUNT = s.ACCOUNT
GROUP BY a.INDUSTRY
ORDER BY BENEFICIO_TOTAL DESC;

-- 4. Reflexión y Sugerencia de Estrategias (SOLO EN EL PDF)







